#!/bin/sh

# this is just an example!
# add your autostart stuffs here
redshift & # blue light filter at night
picom & # Compositor for smooth window spawning and terminal transparency
xmodmap ~/.config/.Xmodmap # swaps Escape and Capslock
xrdb merge ~/.config/.Xresources & # allows terminal to be configured with the values in .config/.Xresources (important for transparency)
feh --bg-fill ~/Pictures/wallpaper/wall.png & # sets background picture
xset r rate 200 50 & # sets keyboard polling rate

# run bar script and dwm ( do not remove this )
bash ~/devel/scripts/system/bar-laptop.sh &  # swap out bar-desktop.sh with bar-laptop.sh when using a laptop for brightness and battery icons
chadwm
