#!/bin/sh

# this is just an example!
# add your autostart stuffs here
redshift &
picom &
xmodmap ~/.config/.Xmodmap
xrdb merge ~/.config/.Xresources &
feh --bg-fill ~/Pictures/wallpaper/wall.png &
xset r rate 200 50 &
# run bar script and dwm ( do not remove this )
bash ~/devel/scripts/system/bar-laptop.sh &  # swap out bar-desktop.sh with bar-laptop.sh when using a laptop for brightness and battery icons
dwm
