#!/bin/bash
if test -f "$1"; then
   echo "$(readlink -f $1)" >> $1
   mv --backup=numbered $1 ~/.trash/
 elif test -d "$1"; then
   echo "$(realpath $1)" >> $1/.trashdir
   mv --backup=numbered $1 ~/.trash/
 else
   echo "file does not exists"
fi
