#!/bin/bash
if [ -z  "$1" ]; then 
  feh --bg-fill ~/Pictures/wallpaper/wall.png
  echo 'No input refreshing background'
else
  cp "$1" ~/Pictures/wallpaper/wall.png
  feh --bg-fill ~/Pictures/wallpaper/wall.png
fi
